name: Build and Upload

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up JDK 16
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 16
          distribution: adopt

      - name: Build with Maven
        run: mvn package

      - name: Upload to Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: SlimeTinker
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}
